# Generated by Django 5.1.2 on 2024-12-06 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_category_city_subcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('name',), 'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
    ]
