# Generated by Django 5.1.2 on 2024-12-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_category_city_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='city',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='city',
            field=models.ManyToManyField(related_name='cities', to='backend.city', verbose_name='Город'),
        ),
    ]
