# Generated by Django 5.1.2 on 2024-12-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_subcategory_city_subcategory_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='working_days',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='is_friday',
            field=models.BooleanField(default=False, verbose_name='Пятница'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='is_monday',
            field=models.BooleanField(default=False, verbose_name='Понедельник'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='is_saturday',
            field=models.BooleanField(default=False, verbose_name='Суббота'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='is_sunday',
            field=models.BooleanField(default=False, verbose_name='Воскресенье'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='is_thursday',
            field=models.BooleanField(default=False, verbose_name='Четверг'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='is_tuesday',
            field=models.BooleanField(default=False, verbose_name='Вторник'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='is_wednesday',
            field=models.BooleanField(default=False, verbose_name='Среда'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='specific_date',
            field=models.DateField(blank=True, null=True, verbose_name='Определенная дата'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='closing_time',
            field=models.TimeField(blank=True, help_text='Пример ввода времени: 10:00:00', null=True, verbose_name='Время закрытия'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='opening_time',
            field=models.TimeField(blank=True, help_text='Пример ввода времени: 10:00:00', null=True, verbose_name='Время открытия'),
        ),
    ]
