# Generated by Django 5.1.2 on 2024-12-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_subcategory_working_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='lunch_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Конец обеда'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='lunch_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Начало обеда'),
        ),
    ]
