# Generated by Django 5.1.2 on 2024-12-14 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_subcategory_lunch_end_subcategory_lunch_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='city',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='backend.city', verbose_name='Город'),
        ),
    ]
