# Generated by Django 5.1.2 on 2024-12-27 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_country_alter_city_options_city_lat_city_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
