# Generated by Django 5.1.2 on 2024-12-28 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_subcategory_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='user',
        ),
    ]
