# Generated by Django 5.1.2 on 2025-01-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_botuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='reservation_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
